Accept the initial design
RTG2717/iso-chidiya-uddi pull request #22
Opened 2024-11-22 22:33 UTC by FlyingSaturn

Made the design using penpot, please accept the design (writing this at 4:02 am so being a bit dizzy rn)

2024-11-22 22:33 UTC, FlyingSaturn commented
You can remove that app.py thing and just keep that one commit

2024-11-23 04:11 UTC, Digit4 requested changes

2024-11-23 04:11 UTC, Digit4 commented on app.py
Remove this file. Keep it with you if you want, but remove this file in git.

2024-11-23 04:11 UTC, Digit4 commented on design/Game Logic/index.html
![image](https://github.com/user-attachments/assets/58a698dd-1404-464e-ad8c-01d025080400)
Is this the design? or I'm missing something? Could you provide screenshot with labels for what all the colored areas represent?

2024-11-23 05:50 UTC, FlyingSaturn commented on app.py
done.

2024-11-23 05:52 UTC, FlyingSaturn commented on design/Game Logic/index.html
it was actually my fault to keep things incomplete like this before submitting PR. Moreover, it uses absolute positioning. I'll try to learn Penpot and then I'll upload a complete PR.

Please decline this PR till then.

2026-08-17 05:31 UTC, closed without merging